<?php
	$arr_prods = [
		[
			'prod_id' => 1,
			'prod_name' => 'Мини юбка, латекс',
            'prod_price' => 1500,
            'prod_desc' => 'Подчеркнёт Вашу фигуру, все будут в ударе',
            'prod_matter' => 'latex',
            'prod_count' => 5,
		],
		[
            'prod_id' => 2,
            'prod_name' => 'Мини юбка, кожа',
            'prod_price' => 1800,
            'prod_desc' => 'Красиво будет сидеть на Вашей фигуру, Вам понравится',
            'prod_matter' => 'leather',
            'prod_count' => 7,
        ],
		[
            'prod_id' => 3,
            'prod_name' => 'Атласные перчатки',
            'prod_price' => 900,
            'prod_desc' => 'Подчеркнёт изящество Ваших рук',
            'prod_matter' => 'satin',
            'prod_count' => 5,
        ],
		[
            'prod_id' => 4,
            'prod_name' => 'Виниловое платье',
            'prod_price' => 1800,
            'prod_desc' => 'Подчеркнёт изящество Ваших рук',
            'prod_matter' => 'vinyl',
            'prod_count' => 8,
        ],
		[
            'prod_id' => 5,
            'prod_name' => 'Виниловая юбка карандаш',
            'prod_price' => 900,
            'prod_desc' => 'Подчеркнёт изящество Ваших рук',
            'prod_matter' => 'vinyl',
            'prod_count' => 0,
        ],
		[
            'prod_id' => 6,
            'prod_name' => 'Чулки из искусственной кожи',
            'prod_price' => 1100,
            'prod_desc' => 'Подчеркнёт изящество Ваших рук',
            'prod_matter' => 'leather',
            'prod_count' => 3,
        ],
		[
            'prod_id' => 7,
            'prod_name' => 'Кожанный комбинизен',
            'prod_price' => 1100,
            'prod_desc' => 'Подчеркнёт изящество Ваших рук',
            'prod_matter' => 'leather',
            'prod_count' => 4,
        ],
		[
            'prod_id' => 8,
            'prod_name' => 'Сахар',
            'prod_price' => 48,
            'prod_desc' => 'Подсластите себе жизнь',
            'prod_matter' => 'weight',
            'prod_count' => 4,
        ],
		[
            'prod_id' => 9,
            'prod_name' => 'Мука',
            'prod_price' => 50,
            'prod_desc' => 'Испечёте что угодно',
            'prod_matter' => 'weight',
            'prod_count' => 4,
        ],
	];
?>